### ISSUE TITLE
How to change Matomo ID while importing

### ISSUE THREAD

**Issue by fjst** [matomo-org/plugin-GoogleAnalyticsImporter#171]
How can i Change the Matomo ID while importing?

**Comment by diosmosis** [comment]
Hi @fjst, unfortunately we don't answer questions in this issue tracker but only handle feature requests or bug reports. You could ask the question in our forum: https://forum.matomo.org/ (it would also help you get a faster answer if you explained in detail what you mean by the "Matomo ID" since I don't know what you mean by that). Thanks for your understanding.
