### ISSUE TITLE
Does importer REPLACE data instead of MERGING data?

### ISSUE THREAD

**Issue by ghnp5** [matomo-org/plugin-GoogleAnalyticsImporter#241]
When I migrated from GA to Matomo,
I set up the Google Analytics Importer from when the GA property started, until "the end" (no specific date).

I saw that GA Importer created a new site, so I simply used that same site ID to track on my live site, so I don't have data split in two different sites on Matomo.

However, now that the GA Importer finally finished importing, it appears that it cleared ALL the data that Matomo has been importing from the live site, since.

I assumed that the GA Importer would merge the data, and not overwrite it!
I saw absolutely no warnings about that, when I set up the importer...

Is there any way to recover the lost data, assuming I have no backups of the Matomo database?

![sshot-2022-04-17-00-08-20-1](https://user-images.githubusercontent.com/57591332/163693911-84f622e0-9448-4e39-8f65-feb431c9815e.jpg)

Thank you.

**Comment by AltamashShaikh** [comment]
@ghnp5 This shouldn't have happened ideally, to get the data back we can try few things if the GA importer has finished importing.
1. Ensure no more importers are running
2. Invalidate the reports since started tracking live data
Refer this [FAQ](https://matomo.org/faq/how-to/faq_155/ ) to invalidate report for that site.
3. Wait for rearchiving to start and complete or manually run the archive command mentioned in the above FAQ

**Comment by ghnp5** [comment]
Thank you very much! That seems to have recovered the data :)

```
php /var/www/html/console core:invalidate-report-data --dates=2022-03-21,2022-04-16 --sites=2

php /var/www/html/console core:archive --force-all-websites --force-date-range=2022-03-21,2022-04-16 --url=...
```
